import type { SxProps, Theme } from '@mui/material';
import { INACTIVITY_COLORS, INACTIVITY_TYPOGRAPHY } from './constants';

const FIGMA_CANVAS_WIDTH = 1440;
const FIGMA_CANVAS_HEIGHT = 900;

export const inactivityStyles: Record<string, SxProps<Theme>> = {
  root: {
    minHeight: { xs: '100dvh', md: `${FIGMA_CANVAS_HEIGHT}px` },
    bgcolor: INACTIVITY_COLORS.pageBackground,
    color: 'common.white',
    width: '100%',
    position: 'relative',
    overflow: 'hidden',
  },
  container: {
    width: '100%',
    maxWidth: `${FIGMA_CANVAS_WIDTH}px`,
    minHeight: { xs: '100dvh', md: `${FIGMA_CANVAS_HEIGHT}px` },
    mx: 'auto',
    position: 'relative',
    px: { xs: 2, sm: 0 },
  },
  logoRow: {
    position: 'absolute',
    top: 'clamp(4px, 2.4dvh, 28px)',
    left: 0,
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoImage: {
    width: {
      xs: 'min(98vw, 760px)',
      sm: 'min(96vw, 1100px)',
      md: 'min(100%, 1440px)',
    },
    maxWidth: 'none',
    height: 'auto',
    display: 'block',
    objectFit: 'contain',
  },
  logoTextBlock: {
    display: 'none',
    flexDirection: 'column',
    alignItems: 'center',
    lineHeight: 1,
  },
  logoTitle: {
    fontSize: INACTIVITY_TYPOGRAPHY.logoTitle.fontSize,
    lineHeight: INACTIVITY_TYPOGRAPHY.logoTitle.lineHeight,
    fontWeight: 700,
    color: INACTIVITY_COLORS.logoText,
  },
  logoSubtitle: {
    fontSize: INACTIVITY_TYPOGRAPHY.logoSubtitle.fontSize,
    lineHeight: INACTIVITY_TYPOGRAPHY.logoSubtitle.lineHeight,
    fontWeight: 600,
    color: INACTIVITY_COLORS.logoText,
  },
  illustrationWrapper: {
    position: 'absolute',
    left: '50%',
    top: { xs: '32%', sm: '33%', md: '34%' },
    transform: 'translate(-50%, -50%)',
    width: { xs: 'min(70vw, 210px)', sm: 'min(50vw, 280px)', md: 'min(31vw, 330px)' },
    height: 'auto',
  },
  illustration: {
    width: '100%',
    height: 'auto',
    objectFit: 'contain',
    display: 'block',
  },
  content: {
    position: 'absolute',
    left: '50%',
    top: { xs: '67%', sm: '69%', md: '69%' },
    transform: 'translate(-50%, -50%)',
    width: { xs: 'min(92vw, 320px)', sm: 410, md: 480 },
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: { xs: '10px', sm: '12px', md: '16px' },
  },
  title: {
    fontSize: INACTIVITY_TYPOGRAPHY.title.fontSize,
    lineHeight: INACTIVITY_TYPOGRAPHY.title.lineHeight,
    fontWeight: 700,
    color: INACTIVITY_COLORS.title,
  },
  description: {
    fontSize: INACTIVITY_TYPOGRAPHY.description.fontSize,
    lineHeight: INACTIVITY_TYPOGRAPHY.description.lineHeight,
    fontWeight: 500,
    color: INACTIVITY_COLORS.description,
  },
  signInLink: {
    minWidth: '100px',
    height: { xs: 30, sm: 32, md: 36 },
    borderRadius: '6px',
    px: { xs: '14px', sm: '16px', md: '20px' },
    py: { xs: '6px', sm: '7px', md: '8px' },
    textDecoration: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: INACTIVITY_TYPOGRAPHY.signInLink.fontSize,
    lineHeight: INACTIVITY_TYPOGRAPHY.signInLink.lineHeight,
    fontWeight: 500,
    color: INACTIVITY_COLORS.buttonText,
    bgcolor: INACTIVITY_COLORS.buttonBg,
    transition: 'background-color 120ms ease',
    '&:hover': {
      bgcolor: INACTIVITY_COLORS.buttonBgHover,
    },
  },
  mobileGradient: {
    display: { xs: 'block', lg: 'none' },
    position: 'absolute',
    inset: 0,
    pointerEvents: 'none',
    background: INACTIVITY_COLORS.mobileGradient,
  },
};
